# Uncomment the next line to define a global platform for your project
# platform :ios, '9.1'

target 'BestIntentions' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BestIntentions

  target 'BestIntentionsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BestIntentionsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BestIntentions WatchKit App' do

end

target 'BestIntentions WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  platform :watchos, '3.1'

  # Pods for BestIntentions WatchKit Extension

end
